### ISSUE TITLE
Support for Unity 6 WebGL builds

### ISSUE THREAD

**Issue by grubFX** [hiukim/unity-webar-foundation#12]
Hi! First of all: thanks for the great work, I bought the asset and it works perfectly when I build WebGL with Unity 2022!

However when I try a WebGL build with the new Unity 6000.0.11f1 preview, the build breaks with the following errors. Maybe there is an easy fix - thanks in advance!

```
Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
error: Assets\WebAR Foundation\Runtime\Plugins\MindARFacePlugin.jslib: failure to execute js library "Assets\WebAR Foundation\Runtime\Plugins\MindARFacePlugin.jslib":
error: Assets\WebAR Foundation\Runtime\Plugins\MindARFacePlugin.jslib: use -sVERBOSE to see more details
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/
with a log of the build and the input files used to run. Exception message: "Assets\WebAR Foundation\Runtime\Plugins\MindARFacePlugin.preprocessed.jslib:1
// ref: https://github.com/yukpiz/unity-webgl-movie/blob/master/Assets/Plugins/WebGLMovieTexture.jslib
^

SyntaxError: Identifier 'plugin' has already been declared
    at Assets\WebAR Foundation\Runtime\Plugins\MindARFacePlugin.preprocessed.jslib:1:1
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.load (D:\Unity\Hub\6000.0.11f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\src\modules.js:226:12)
    at runJSify (D:\Unity\Hub\6000.0.11f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\src\jsifier.js:95:18)
    at Object.<anonymous> (D:\Unity\Hub\6000.0.11f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\src\compiler.js:109:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
emcc: error: 'D:/Unity/Hub/6000.0.11f1/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/node/node.exe D:\Unity\Hub\6000.0.11f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\src\compiler.js C:\<redacted>\AppData\Local\Temp\tmpm42nhdtd.json --symbols-only' failed (returned 1)

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

**Comment by grubFX** [comment]
I managed to workaround this error by inlining the defintions of the plugins, to prevent duplicate definitions of the "plugin" variable in `MindARFacePlugin.jslib` and `MindARImagePlugin.jslib`. The WebGL builds are now running perfectly fine also on Unity 6000.0.12 👍

![image](https://github.com/user-attachments/assets/6f5f68ad-a612-4856-aa44-6db204ca57a0)
